
export { default as Login} from '../pages/auth/LoginPage'
export { default as RegisterPage} from '../pages/auth/RegisterPage'
export { default as ForgetPasswordPage} from './auth/ForgetPasswordPage'
export { default as ExpenseReportPage} from './reports/expense/ExpenseReportPage'
export { default as ExpenseForm} from './reports/expense/ExpenseForm'
export { default as entrada} from './reports/IncomReportPage'
export { default as category} from './reports/CategoryPage'
export { default as account }  from './reports/AccountPage'
export { default as dashboard} from './DashboardPage'
export { default as settings} from './SettingsPage'
export { default as profile} from './ProfilePage'
export { default as totlReport} from './reports/TotalReportPage'
