export { default as Header} from './Header'
export { default as Footer} from './Footer'
export { default as Sidebar} from './Sidebar'
export { default as CardInfor} from './CardInfor'
export { default as CardInfor2} from './CardInfor2'